version: 2.1

commands:
  pull-merge:
    description: "Bring the repository up-to-date with master and handle setup"
    steps:
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.lock" }}
      - run:
          name: Configure the CircleCI git user
          command: |
            git config --global user.email "ci@medology.com"
            git config --global user.name "Circle CI"
      - run:
          name: Configure git to use SSH instead of HTTP
          command: |
            git config --global url.git@github.com:.insteadOf git://github.com/
            git config --global --add url.git@github.com:.insteadOf https://github.com/
      - run:
          name: Merge master
          command: git fetch origin && git merge origin/master --no-edit

  ##################
  # GCloud commands
  ##################
  gcloud_configure:
    description: Configure GCloud
    steps:
      - run:
          name: Configure GCloud
          command: configure_gcloud.sh

executors:
  ubuntu:
    environment:
      PATH: /opt/circleci/.pyenv/shims:./bin:./vendor/bin:./submodules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:./node_modules/.bin
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp/FlexibleMink

jobs:
  build:
    description: "Build the project."
    parallelism: 1
    executor: ubuntu
    steps:
      - pull-merge
      - run:
          name: Add in submodules
          command: git submodule update --init
      - run:
          name: Initialize docker .env
          command: bin/init/init_docker_env.sh
      - gcloud_configure
      - run:
          name: Start containers
          command: |
            .circleci/containers up -d
            submodules/bin/init/wait_for_services.sh
      - run:
          name: Initialize the project
          command: |
            mkdir -p /tmp/artifacts
            bin/init_project
      - run:
          name: Run style fixer
          command: ci-style-fixer
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer/cache

  test:
    description: "Test the project."
    parallelism: 1
    executor: ubuntu
    steps:
      - attach_workspace:
          at: .
      - gcloud_configure
      - run:
          name: Start containers
          command: |
            .circleci/containers up -d
            submodules/bin/init/wait_for_services.sh
      - run:
          name: Unit tests
          command: phpunit --log-junit /tmp/artifacts/phpunit.junit.xml -strict-coverage
      - run:
          name: Behat tests
          command: behat --strict -vv -f pretty -o std -f junit -o /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-and-test:
    jobs:
    - build:
        context:
          - org-global
    - test:
        context:
          - org-global
        requires:
          - build
