version: '3.9'

services:
  web:
    image: httpd:2
    volumes:
      - ..:/data
      - ../web:/usr/local/apache2/htdocs:ro
    env_file: .env
    ports:
      - 80:80

  chrome:
    image: selenium/standalone-chrome-debug:2.53.1
    depends_on:
      - web
    environment:
      - no_proxy:localhost
    links:
      - web
    volumes:
      - /dev/shm:/dev/shm
      - ..:/data
    env_file: .env
    ports:
      - 4444:4444
      - 5900:5900

networks:
  default:
    external:
      name: global
